#=================================================================================#
# LICENSE (MIT)                                                                   #
#=================================================================================#
#                                                                                 #
# The MIT License (MIT)                                                           #
#                                                                                 #
# Copyright (c) 2026 luau-project https://github.com/luau-project/lua-latin1-utf8 #
#                                                                                 #
# Permission is hereby granted, free of charge, to any person obtaining a copy    #
# of this software and associated documentation files (the "Software"), to deal   #
# in the Software without restriction, including without limitation the rights    #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell       #
# copies of the Software, and to permit persons to whom the Software is           #
# furnished to do so, subject to the following conditions:                        #
#                                                                                 #
# The above copyright notice and this permission notice shall be included in all  #
# copies or substantial portions of the Software.                                 #
#                                                                                 #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR      #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,        #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE     #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER          #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,   #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE   #
# SOFTWARE.                                                                       #
#                                                                                 #
#=================================================================================#

__EMPTY =
DIRSEP = \$(__EMPTY)
SystemDrive = c:
WINDIR = $(SystemDrive)$(DIRSEP)windows
PROGRAMFILES = $(SystemDrive)$(DIRSEP)Program Files
SHELL = $(WINDIR)$(DIRSEP)System32$(DIRSEP)cmd.exe
OPENARGDELIMITER = "
CLOSEARGDELIMITER = $(OPENARGDELIMITER)

PREFIX = $(DIRSEP)usr$(DIRSEP)local
MULTILIB = lib

LUA_DIR = $(PREFIX)
LUA = lua
LUA_VERSION = 5.1
LUA_INCSUBDIR = include
LUA_INCDIR = $(LUA_DIR)$(DIRSEP)$(LUA_INCSUBDIR)
LUA_LIBDIR = $(LUA_DIR)$(DIRSEP)$(MULTILIB)
INSTALL_LMODSUBDIR = bin$(DIRSEP)lua
INSTALL_LMOD = $(LUA_DIR)$(DIRSEP)$(INSTALL_LMODSUBDIR)

PACKAGE_NAME = lua-latin1-utf8
PACKAGE_VERSION = 0.1.0
PACKAGE_REVISION = 1
PACKAGE_REPOSITORY_URL = https://github.com/luau-project/$(PACKAGE_NAME)
PACKAGE_SOURCE_URL = git+$(PACKAGE_REPOSITORY_URL).git
PACKAGE_DEV_BRANCH = main
PACKAGE_HOMEPAGE_URL = $(PACKAGE_REPOSITORY_URL)
ROCKSPEC_EXT = .rockspec
ROCKSPEC_DIR = rockspecs
ROCKSPEC_TEMPLATE = $(ROCKSPEC_DIR)$(DIRSEP)rockspec.in
DEV_ROCKSPEC_VERSION = dev
DEV_ROCKSPEC_REVISION = 1
DEV_ROCKSPEC = $(ROCKSPEC_DIR)$(DIRSEP)$(PACKAGE_NAME)-$(DEV_ROCKSPEC_VERSION)-$(DEV_ROCKSPEC_REVISION)$(ROCKSPEC_EXT)
VERSIONED_ROCKSPEC = $(ROCKSPEC_DIR)$(DIRSEP)$(PACKAGE_NAME)-$(PACKAGE_VERSION)-$(PACKAGE_REVISION)$(ROCKSPEC_EXT)

SRCDIR = src
OUTBASENAME = $(PACKAGE_NAME).lua
LUA_LATIN1_UTF8_SRC = $(SRCDIR)$(DIRSEP)$(OUTBASENAME)

TESTFILE = test.lua
TESTCOVARG = --coverage

COVRUNNER = luacov
COVRUNNER_ARGS =
COVSTATS = luacov.stats.out
COVREPORT = luacov.report.out

LUAROCKS = luarocks
LUAROCKS_LINT_ARGS =
LUAROCKS_MAKE_ARGS =
LUAROCKS_REMOVE_ARGS =

REDIRTOSTDOUT = >

SED = $(OPENARGDELIMITER)$(PROGRAMFILES)$(DIRSEP)Git$(DIRSEP)usr$(DIRSEP)bin$(DIRSEP)sed.exe$(CLOSEARGDELIMITER)
SEDEFLAG = -e

ECHO = echo

RM = del
RMFLAGS = /Q

MKDIR = mkdir
MKDIRFLAGS =

INSTALL = copy
INSTALLFLAGS = /Y

all: install

create-install-dir:
	-$(MKDIR) $(MKDIRFLAGS) $(OPENARGDELIMITER)$(INSTALL_LMOD)$(CLOSEARGDELIMITER)

install: create-install-dir
	$(INSTALL) $(INSTALLFLAGS) $(LUA_LATIN1_UTF8_SRC) $(OPENARGDELIMITER)$(INSTALL_LMOD)$(CLOSEARGDELIMITER)

uninstall:
	-$(RM) $(RMFLAGS) $(OPENARGDELIMITER)$(INSTALL_LMOD)$(DIRSEP)$(OUTBASENAME)$(CLOSEARGDELIMITER)

test: $(TESTFILE) $(LUA_LATIN1_UTF8_SRC)
	$(LUA) $(TESTFILE)

coverage: $(COVREPORT)

$(COVREPORT): $(COVSTATS)
	$(COVRUNNER) $(COVRUNNER_ARGS)

$(COVSTATS): $(TESTFILE) $(LUA_LATIN1_UTF8_SRC)
	$(LUA) $(TESTFILE) $(TESTCOVARG)

luarocks-install-dev: $(DEV_ROCKSPEC)
	$(LUAROCKS) make $(LUAROCKS_MAKE_ARGS) $(DEV_ROCKSPEC)

luarocks-install: $(VERSIONED_ROCKSPEC)
	$(LUAROCKS) make $(LUAROCKS_MAKE_ARGS) $(VERSIONED_ROCKSPEC)

luarocks-uninstall-dev:
	$(LUAROCKS) remove $(LUAROCKS_REMOVE_ARGS) $(DEV_ROCKSPEC)

luarocks-uninstall:
	$(LUAROCKS) remove $(LUAROCKS_REMOVE_ARGS) $(VERSIONED_ROCKSPEC)

lint-rockspecs: lint-dev-rockspec lint-rockspec

lint-dev-rockspec: $(DEV_ROCKSPEC)
	$(LUAROCKS) lint $(LUAROCKS_LINT_ARGS) $(DEV_ROCKSPEC)

lint-rockspec: $(VERSIONED_ROCKSPEC)
	$(LUAROCKS) lint $(LUAROCKS_LINT_ARGS) $(VERSIONED_ROCKSPEC)

create-rockspecs: create-dev-rockspec create-rockspec

create-dev-rockspec: $(DEV_ROCKSPEC)

create-rockspec: $(VERSIONED_ROCKSPEC)

echo-rockspec:
	@$(ECHO) $(VERSIONED_ROCKSPEC)

echo-dev-rockspec:
	@$(ECHO) $(DEV_ROCKSPEC)

$(DEV_ROCKSPEC): $(ROCKSPEC_TEMPLATE)
	$(SED) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_NAME@|$(PACKAGE_NAME)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_VERSION@|$(DEV_ROCKSPEC_VERSION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REVISION@|$(DEV_ROCKSPEC_REVISION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REPOSITORY_URL@|$(PACKAGE_REPOSITORY_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_URL@|$(PACKAGE_SOURCE_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_DEV_BRANCH@|$(PACKAGE_DEV_BRANCH)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_HOMEPAGE_URL@|$(PACKAGE_HOMEPAGE_URL)|g$(CLOSEARGDELIMITER) $(ROCKSPEC_TEMPLATE)$(REDIRTOSTDOUT) $(DEV_ROCKSPEC)

$(VERSIONED_ROCKSPEC): $(ROCKSPEC_TEMPLATE)
	$(SED) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_NAME@|$(PACKAGE_NAME)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_VERSION@|$(PACKAGE_VERSION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REVISION@|$(PACKAGE_REVISION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REPOSITORY_URL@|$(PACKAGE_REPOSITORY_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_URL@|$(PACKAGE_SOURCE_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_DEV_BRANCH@|$(PACKAGE_DEV_BRANCH)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_HOMEPAGE_URL@|$(PACKAGE_HOMEPAGE_URL)|g$(CLOSEARGDELIMITER) $(ROCKSPEC_TEMPLATE)$(REDIRTOSTDOUT) $(VERSIONED_ROCKSPEC)

clean-cov-stats:
	-$(RM) $(RMFLAGS) $(COVSTATS)

clean-cov-report:
	-$(RM) $(RMFLAGS) $(COVREPORT)

clean-coverage: clean-cov-stats clean-cov-report

clean-dev-rockspec:
	-$(RM) $(RMFLAGS) $(DEV_ROCKSPEC)

clean-rockspec:
	-$(RM) $(RMFLAGS) $(VERSIONED_ROCKSPEC)

clean: clean-coverage

very-clean: clean clean-dev-rockspec clean-rockspec
