name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:

      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - luajit
          - openresty

        toolchain:
          - msvc
          - cc

        exclude:
          - os: ubuntu-latest
            toolchain: msvc

          - os: macos-latest
            toolchain: msvc
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup MSVC
        uses: step-security/msvc-dev-cmd@22c98154b708dbd743e6f27a933cf6ceba3305c4 # v1.31.1
        if: runner.os == 'Windows' && matrix.toolchain == 'msvc'

      - name: Setup Lua and LuaRocks
        uses: luau-project/setup-lua@ebdc724769a3976b27abe70d93a730aede440ba9 # v2.0.8
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Set environment variable to hold the rockspec name (Unix)
        if: runner.os != 'Windows'
        run: |
          if test "$GITHUB_REF_TYPE" = "tag"; then
            echo "ROCKSPEC=$(make -f Makefile.unix echo-rockspec)" >> $GITHUB_ENV
          else
            echo "ROCKSPEC=$(make -f Makefile.unix echo-dev-rockspec)" >> $GITHUB_ENV
          fi

      - name: Set environment variable to hold the rockspec name (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          IF "%TOOLCHAIN%" EQU "msvc" (
            SET "MAKE_PROG=nmake"
            SET "MAKE_FILE_FLAG=/F"
          ) ELSE IF "%TOOLCHAIN%" EQU "cc" (
            SET "MAKE_PROG=mingw32-make"
            SET "MAKE_FILE_FLAG=-f"
          ) ELSE (
            ECHO Unknown matrix.toolchain: %TOOLCHAIN%
            EXIT /B 1
          )

          IF "%GITHUB_REF_TYPE%" EQU "tag" (
            SET "MAKE_TARGET=echo-rockspec"
          ) ELSE (
            SET "MAKE_TARGET=echo-dev-rockspec"
          )

          @FOR /F "TOKENS=* USEBACKQ" %%F IN (`%MAKE_PROG% %MAKE_FILE_FLAG% Makefile.win %MAKE_TARGET%`) ^
          DO @ECHO ROCKSPEC=%%F>>%GITHUB_ENV%

      - name: Lint (Unix)
        if: runner.os != 'Windows'
        run: luarocks lint "$ROCKSPEC"

      - name: Lint (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: luarocks lint "%ROCKSPEC%"

      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: luarocks make "$ROCKSPEC"

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: luarocks make "%ROCKSPEC%"

      - name: Install luacov to run tests with code coverage
        run: luarocks install luacov

      - name: Run tests with code coverage
        run: lua "test.lua" --coverage

      - name: Run the sample code out of the tree (Unix)
        if: runner.os != 'Windows'
        run: |
          cd "$RUNNER_TEMP"
          lua "$GITHUB_WORKSPACE/sample.lua"

      - name: Run the sample code out of the tree (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd "%RUNNER_TEMP%"
          lua "%GITHUB_WORKSPACE%\sample.lua"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
